### ISSUE TITLE
Potential bug in feature_extract.py 

### ISSUE THREAD

**Issue by julianzaidi** [kan-bayashi/PytorchWaveNetVocoder#25]
I think there is a bug in the method `convert_continuos_f0(f0)` in `feature_extract.py ` (line 122 - 124):

`if f0.all() == 0:
        print("WARNING: all of the f0 values are 0.")
        return uv, f0` 

if I understand, you want to avoid converting F0 to continuous F0 if all the F0 values are equal to 0. However, `f0.all()` check if ALL the values in the array are True (i.e are different from 0). If only one value is equal to 0, it will return False and `f0.all() == 0` will then return True. 

I don't know if it is wanted, but in most of the cases your F0 curve will not be continuous.

**Comment by kan-bayashi** [comment]
Thank you for your kind comments!
I misunderstood `.all()` function.
It should be `(f0 == 0).all()`, right?
I will fix it.

**Comment by kan-bayashi** [comment]
@julianzaidi I've fixed. Thank you.

**Comment by julianzaidi** [comment]
Yes exactly @kan-bayashi ! No problem, it's a pleasure to help you.
