### ISSUE TITLE
Failed building wheel for pyworld and dtw-c

### ISSUE THREAD

**Issue by Mark-Leisten-ajalaco** [kan-bayashi/PytorchWaveNetVocoder#50]
Hi I followed this instrcutions to setup:

$ git clone https://github.com/kan-bayashi/PytorchWaveNetVocoder.git
$ cd PytorchWaveNetVocoder/tools
$ make

however this resulted in the following errors:

  x86_64-linux-gnu-gcc: error: pyworld/pyworld.cpp: No such file or directory
  x86_64-linux-gnu-gcc: fatal error: no input files
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyworld
  Running setup.py clean for pyworld
  Building wheel for dtw-c (setup.py) ... error
  Complete output from command /home/ubuntu/Projects/NLP/ajalaSpeech/TTS/experiments/wavenet_vocoder/PytorchWaveNetVocoder/tools/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mnveb40h/dtw-c/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-b0fie57u --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/dtw_c
  copying dtw_c/__init__.py -> build/lib.linux-x86_64-3.6/dtw_c
  running build_ext
  building 'dtw_c.dtw_c' extension
  error: unknown file type '.pyx' (from 'dtw_c/dtw_c.pyx')
  
  ----------------------------------------
  Failed building wheel for dtw-c
  Running setup.py clean for dtw-c
Failed to build pyworld dtw-c

Do these final messages in the stdout indicate that the earlier build/ compilation failures are rectified by a sanity check?

  Running setup.py install for pyworld ... done
  Running setup.py install for dtw-c ... done
Successfully installed PyWavelets-1.0.2 audioread-2.1.6 cffi-1.12.2 cycler-0.10.0 cython-0.29.6 decorator-4.4.0 dtw-1.3.3 dtw-c-0.6.0 fastdtw-0.3.2 h5py-2.9.0 imageio-2.5.0 joblib-0.13.2 kiwisolver-1.0.1 librosa-0.6.3 llvmlite-0.28.0 matplotlib-3.0.3 networkx-2.2 numba-0.43.1 numpy-1.13.3 pillow-6.0.0 pycparser-2.19 pyparsing-2.4.0 pysptk-0.1.16 python-dateutil-2.8.0 pyworld-0.2.8 pyyaml-5.1 resampy-0.2.1 scikit-image-0.15.0 scikit-learn-0.20.3 scipy-1.2.1 six-1.12.0 soundfile-0.10.2 sprocket-vc-0.18.2 torch-1.0.1.post2 torchvision-0.2.2.post3
touch venv/bin/activate

Or do I have a faulty build here?

Any help would be appreciated!

**Comment by kan-bayashi** [comment]
It is no problem.
The installation is successfully done according to following lines:

```bash
Running setup.py install for pyworld ... done
Running setup.py install for dtw-c ... done
```
