### ISSUE TITLE
could not find wav folder

### ISSUE THREAD

**Issue by james20141606** [kan-bayashi/PytorchWaveNetVocoder#65]
Hey, thanks for the amazing repo on wavenet vocoder. I have tried your https://github.com/kan-bayashi/PytorchWaveNetVocoder/blob/master/egs/arctic/si-open-melspc/run.sh to run the stage. When I run stage 1, one error occured.

the codes here:
```
# make scp files
    if [ ${highpass_cutoff} -eq 0 ];then
        cp "data/${train}/wav.scp" "data/${train}/wav_hpf.scp"
    else
        find "wav/${train}" -name "*.wav" | sort > "data/${train}/wav_hpf.scp"
    fi
```
will execute else part and find `wav` folder's files. However, there is no wav folder created before so I could not find it. Could you please help with it?

**Comment by kan-bayashi** [comment]
Thank you for your report.
Sorry, this is my typo.
Fixed in #66.
